### ISSUE TITLE
Add pinch/zoom support 

### ISSUE THREAD

**Issue by fukhaos** [brutaldesign/swipebox#1]
Should be nice add pinch/zoom support in mobile.

**Comment by clixclix2** [comment]
Hi, I've developed the pinch-zoom feature on swipebox v.1.4.1
It works fine on iOS and Android devices.
However, I'm not skilled on grunt things, so I've released the patch here: https://www.itala.net/blog/art-8-pinch-zoom-per-swipebox
I've identified the modified code with special tags, so that the patch can be easily applied to the official release or on future releases.
Please feel free to pull the patch on the official release.

**Comment by themedotal** [comment]
@clixclix2 Thanks works fine on android as im testing

**Comment by madurapa** [comment]
@clixclix2 Thanks bro! works fine on Android

**Comment by vegenex** [comment]
**@clixclix2** Thanx it works good on iOs
