### ISSUE TITLE
Autoplay videos

### ISSUE THREAD

**Issue by davidmles** [brutaldesign/swipebox#181]
It would be amazing to have an option to autoplay videos once the thumbnail is clicked, so the user doesn't have to click twice to watch it (first click to open swipebox and the second click to play the video).

Is there a hidden option to enable this? Any workaround besides modifying the source code?

**Comment by Guillom** [comment]
Hi,

Add param in the getVideo function.
```
...if (youtubeUrl) {
iframe = '<iframe width="480" height="360" src="//www.youtube.com/embed/' + youtubeUrl[1] + '?fs=1&autohide=1&autoplay=1&rel=0&showinfo=0" frameborder="0" allowfullscreen></iframe>'
} else if (vimeoUrl)...
```

**Comment by EZWrighter** [comment]
This autoplay works great, unless there is more than one video.  If you have 3 videos in a gallery, select the middle one, all three videos will start playing due to the preload functionality.  I have forked and am adding an event trigger for leaving a slide for stopping video play and for moving to a new slide for playing a video.  This should allow for me to pass messages to the iframe to control video playback.

**Comment by davidmles** [comment]
I hope your fork gets merged @EZWrighter, thanks.
I'm closing this issue since it was already merged.
