### ISSUE TITLE
iPhone bottom menu covering close button

### ISSUE THREAD

**Issue by wgoodman** [brutaldesign/swipebox#92]
I love swipebox, it does exactly what I want it to do, except in testing on iPhone the close button is being covered by the iPhone bottom menu. Since you can't scroll vertically in swipe box it is difficult to remove the menu. I tried to play with the css, but I can't get it to not cover it up. If I switch from portrait to landscape a couple of times the close button appears above the menu, but initially it does not. Does anyone have any idea on how to trouble shoot this?

**Comment by mysecretstudio** [comment]
Hi guys. Its really quite simple to fix this issue. I've just done it having come across this post and thought i'd fix it. 

Its quite simply the css yes you're right. the issue i was having was when i edited the positioning of the bottom action bar it would move the top bar captions section.

so all you need to do is separate those two css classes/id's

it was bugging me how yes the bottom actions bar would move up to the right level but wouldn't dissappear fully because it was being controlled by some other wizardry. so I did this.

#swipebox-action {
	position: absolute;
	left: 0;
	z-index: 999;
	height: 100px;
	width: 100%;
}

#swipebox-caption {
	position: absolute;
	left: 0;
	z-index: 999;
	height: 50px;
	width: 100%;
}

#swipebox-action {
	bottom: -100px;
}

let me know if it works for you.

cheers
mysecretstudio
